export enum ErrorCode {
  // General
  UNDEFINED_ERROR = 'UNDEFINED_ERROR',
  SERVICE_ERROR = 'SERVICE_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  // Auth
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTED = 'USER_EMAIL_EXISTED',
  USER_USERNAME_EXISTED = 'USER_USERNAME_EXISTED',
  USER_PHONE_EXISTED = 'USER_PHONE_EXISTED',
  USER_PASSWORD_INCORRECT = 'USER_PASSWORD_INCORRECT',
  USER_PASSWORD_MISMATCH = 'USER_PASSWORD_MISMATCH',

  // Document
  DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND',
  DOCUMENT_UPLOAD_FAILED = 'DOCUMENT_UPLOAD_FAILED',

  // Chat
  CHAT_MESSAGE_EMPTY = 'CHAT_MESSAGE_EMPTY',
  CHAT_CONVERSATION_NOT_FOUND = 'CHAT_CONVERSATION_NOT_FOUND',

  // RAG
  RAG_EMBEDDING_FAILED = 'RAG_EMBEDDING_FAILED',
  RAG_VECTOR_SEARCH_FAILED = 'RAG_VECTOR_SEARCH_FAILED',
}
